use crate::grid::{CriterionBuilder, GridInfo, Section};

pub fn build() -> GridInfo {
    let mut b = CriterionBuilder::new();

    GridInfo {
        id: "officine".into(),
        name: "Inspection Officine".into(),
        code: "IP-F-0018".into(),
        version: "1".into(),
        description: "Grille d'inspection des officines de pharmacie selon les BPDisp".into(),
        icon: "💊".into(),
        color: "#22c55e".into(),
        sections: vec![
            Section { id: 1, title: "Renseignements généraux".into(), items: vec![
                b.pre("Loi N° 2021-03 Art 46", "Identification de la structure (Dénomination)"),
                b.item("Loi N° 2021-03 Art 61, 62", "Mode d'acquisition (licences) : Création / Transfert / Rachat-Cession"),
                b.item("", "Statut ou mode d'exploitation : Entreprise individuelle / SARL-U / SARL-P / Autre"),
                b.item("Loi N° 2021-03 Art 62", "Quitus d'exploitation"),
                b.item("", "Adresse, Tel, Mail, BP, GPS"),
                b.item("Loi N° 2021-03 Art 59,62 ; BPDisp 4.4", "Localisation : Département, Commune, Ville, Arrondissement, Quartier/Village, Zone sanitaire"),
                b.item("", "L'intitulé de l'attribution de programmation correspond au site choisi"),
                b.item("Loi N° 2021-03 Art 65", "Horaires d'ouverture au public affichés"),
                b.item("Loi N° 2021-03 Art 65 ; BPDisp 1.14", "Participation au service de garde – Programme de garde affiché"),
            ]},
            Section { id: 2, title: "Système de management de la qualité".into(), items: vec![
                b.pre("Loi N°2021-03 art 1 ; BPDisp 1.3 à 1.5", "Le pharmacien d'officine a mis en place un SMQ ? La documentation est-elle complète ?"),
                b.pre("BPDisp 1.6", "L'officine est dotée d'un Responsable Management Qualité (RMQ) ?"),
                b.pre("BPDisp 1.16", "L'officine est dotée d'un système de gestion de risque qualité"),
                b.item("BPDisp 1.15 à 1.17", "Le système en place permet de garantir et de sauvegarder en toute circonstance la vie et la sécurité du patient"),
                b.pre("BPDisp 1.31a, f", "Les moyens nécessaires sont disponibles pour la mise en œuvre de l'acte pharmaceutique et son homogénéité"),
                b.pre("BPDisp 1.31g, 7.21, 7.27", "Les moyens nécessaires sont disponibles pour la traçabilité de l'acte pharmaceutique y compris les interventions pharmaceutiques"),
            ]},
            Section { id: 3, title: "Personnel".into(), items: vec![
                b.pre("BPDisp 2.2", "L'officine dispose de personnel en nombre suffisant possédant les qualifications nécessaires ainsi qu'une expérience pratique ?"),
                b.pre("BPDisp 2.3", "Organigramme établi et affiché ? Missions et fonctions individuelles clairement définies et décrites par écrit (Fiche de fonction) ?"),
                b.pre("BPDisp 2.4", "Tous les pharmaciens de l'équipe officinale sont inscrits à l'Ordre des pharmaciens ?"),
                b.item("BPDisp 2.9, 2.10", "Présence du pharmacien (Exercice personnel)"),
                b.item("Décret 1296 du 06 nov 2024 Art 16 à 20", "Respect des conditions d'assistance au pharmacien titulaire"),
                b.item("Loi N° 2021-03 Art 63 ; Ord n°73-30 art 18 ; Décret 1296 Art 21-24 ; BPDisp 2.5", "Respect des conditions de remplacement : Notification, Durée, Identité du remplaçant, Motif"),
                b.item("BPDisp 2.11", "Port de l'insigne et/ou badge professionnel indiquant la qualification"),
                b.item("BPDisp 2.12", "Entretien annuel, définition des objectifs et fixation des moyens de réalisation"),
                b.pre("BPDisp 2.8", "Formation initiale ? Adaptée ?"),
                b.pre("BPDisp 2.14 à 2.20", "Formation continue ? Plan de formation ? Adaptée ? Couvre l'ensemble du personnel"),
                b.item("BPDisp 2.18", "Enregistrement et suivi des formations (attestations, comptes rendus, évaluation de l'efficacité)"),
                b.item("BPDisp 2.21", "Procédures relatives à la santé et à l'hygiène du personnel ? Hygiène adaptée (blouse, etc.) ? Visite médicale ?"),
            ]},
            Section { id: 4, title: "Documentation".into(), items: vec![
                b.pre("LOI N° 97-025 art 54,69-71 ; Décret 1296 Art 28 ; BPDisp 3.4-3.9", "Ordonnancier (à conserver 10 ans) : côté et paraphé, sans rature ni blanc, renseignements complets"),
                b.pre("", "Registre spécial des stupéfiants (registre comptable, conserver 10 ans) : côté et paraphé, renseignements complets"),
                b.pre("BPDisp 3.6, 3.7", "Registre des médicaments dérivés du sang (conserver 40 ans)"),
                b.pre("BPDisp 3.4a", "Registre de préparation magistrale ou officinale"),
                b.item("BPDisp 3.11, 3.12", "Copies des ordonnances à conserver 3 ans"),
                b.pre("", "Autres documents officiels : Pharmacopée, Textes règlementaires, Liste nationale des médicaments, Bonnes pratiques"),
                b.pre("BPDisp 1.22-1.28, 3.13-3.15", "Disponibilité des procédures couvrant tout ce qui influence la qualité (Dispensation, Stockage, Chaîne du froid, Préparation, Hygiène…)"),
                b.pre("BPDisp 3.16 à 3.20", "Maîtrise documentaire"),
                b.pre("BPDisp 3.22", "Évaluation périodique"),
                b.pre("BPDisp 3.23", "Gestion des modifications des documents"),
                b.pre("BPDisp 3.21", "Tous les documents sont approuvés, codifiés, datés et signés par le rédacteur et l'approbateur"),
                b.item("BPDisp 3.24, 3.26", "Gestion de la diffusion / Responsabilité du RMQ"),
                b.item("BPDisp 3.25, 3.27", "Gestion du cycle de vie des documents y compris les retraits"),
                b.item("BPDisp 3.13, 3.14, 3.10", "Disponibilité des enregistrements (traçabilité, registres)"),
                b.item("BPDisp 2.13, 3.12, 3.16", "Gestion des archives"),
                b.item("BPDisp 3.28 à 3.31", "Documents informatifs, éducatifs et préventifs pour la santé publique"),
            ]},
            Section { id: 5, title: "Locaux et équipements".into(), items: vec![
                b.pre("Loi N° 2021-03 Art 46", "Emblème (croix grecque verte), Enseigne (« pharmacie »), Plaque d'identification"),
                b.pre("Ord 73-30 art 25 ; BPDisp 4.1-4.22 ; Décret 1296 Art 26", "Propreté et adéquation des locaux, Accessibilité, Conformité au plan du dossier ABMed"),
                b.pre("BPDisp 4.7", "Respect des obligations de stockage : Gaz médicaux/inflammables, Produits à haute toxicité"),
                b.pre("BPDisp 4.7, 4.8", "Respect des obligations de sécurité : Systèmes de sécurité, Issue(s) de secours"),
                b.pre("BPDisp 4.6, 4.16", "Disposition des médicaments de médication officinale et réservés ; Vitrines visibles de l'extérieur"),
                b.pre("BPDisp 3.15, 4.10", "Séparation de la zone de préparation, délimitation du plan de travail, surfaces propres"),
                b.pre("BPDisp 4.18", "Éclairage, stockage lumière/humidité, contrôle température et humidité"),
                b.pre("BPDisp 4.21", "Sanitaires, vestiaires, zone de restauration"),
                b.pre("BPDisp 1.7, 4.23", "Matériel qualifié et adapté ; Enceintes réfrigérées ; Glacière isotherme"),
                b.item("BPDisp 4.24", "Matériel maintenu propre, en bon état ; Procédures de fonctionnement, nettoyage, entretien"),
                b.item("BPDisp 4.25", "Étalonnage/calibration des équipements de mesure"),
                b.item("BPDisp 4.26, 4.27", "Système informatisé validé par l'autorité compétente"),
                b.item("BPDisp 4.30", "Contrat fournisseur système informatisé"),
                b.item("BPDisp 4.33", "Procédure d'accès informatique, codes personnels"),
                b.item("BPDisp 4.34, 4.35", "Sauvegarde des données (fiable, externe, hors officine)"),
                b.item("BPDisp 4.36", "Mesures de remplacement en cas de défaillance ; Gestion coupures électricité"),
                b.item("Décret 1296 Art 34 à 37", "Vente en ligne ? Autorisation ABMed ?"),
            ]},
            Section { id: 6, title: "Approvisionnement".into(), items: vec![
                b.item("BPDisp 5.1, 5.2", "Stock minimum de sécurité (urgence : douleur, diabète, allergie…)"),
                b.item("BPDisp 5.3, 5.4 ; Loi N°2021-03 Art 58", "Commerce hors liste médicaments et remède secret"),
                b.item("BPDisp 5.7, 5.8, 5.9", "Processus de commandes, sélection fournisseurs, importation (AMM, AC, ASI, AE)"),
                b.item("Loi N° 97-025 art 68", "Commandes de stupéfiants : carnet à souches (conserver 10 ans)"),
                b.item("BPDisp 5.10, 5.13", "Conditions de transport et vérification qualité réception"),
                b.item("BPDisp 5.11", "Réception hors heures d'ouverture : isolement sécurisé"),
                b.pre("BPDisp 5.12", "Colis livrés réceptionnés, vérifiés et stockés en attente de contrôle"),
            ]},
            Section { id: 7, title: "Sous-traitance".into(), items: vec![
                b.item("Annexe 6.13, 6.4, 6.10", "Contrat ? Adéquation ? Respect des conditions ? Preuves (rapport d'audit)"),
            ]},
            Section { id: 8, title: "Dispensation".into(), items: vec![
                b.item("Loi N° 97-025 Art 51-54,57 ; Loi N° 2021-03 Art 17 ; BPO 7.1-7.51", "Dispensation des substances vénéneuses (liste I, II, stupéfiants) sur ordonnance obligatoire"),
                b.item("", "Première délivrance listes I et II : ordonnance de moins de 3 mois"),
                b.item("", "Renouvellement liste II : respect posologie et quantités, max 12 mois"),
                b.item("BPDisp 7.14, 7.15", "Le pharmacien assure intégralement l'acte de dispensation conforme aux bonnes pratiques"),
                b.item("BPDisp 7.16", "Surveillance et contrôle de l'exécution de la dispensation"),
                b.item("BPDisp 7.17", "Substitution : accord prescripteur (sauf urgence et intérêt du patient)"),
                b.item("BPDisp 7.18", "Refus de dispenser en cas de risque pour le patient"),
                b.item("BPDisp 7.19 à 7.42", "Acte complet : analyse, vérification, enregistrement, conseils, préparation des doses"),
                b.item("BPDisp 7.34", "Mentions après exécution : timbre, N° enregistrement, date, quantités délivrées"),
                b.item("", "Dispensation exceptionnelle pour traitement chronique"),
                b.item("", "Dispositions spécifiques médicaments vétérinaires"),
                b.item("", "Dispositions DM, DM-DIV, laits infantiles, pansements, cosmétiques, compléments"),
                b.item("Loi n°97-025 ; BPDisp 7.36", "Dispensation stupéfiants : prescription en toutes lettres, carnet à souches"),
                b.item("BPDisp 7.43-7.48", "Conseil, évaluation usage détourné, dossier pharmaceutique, historique"),
                b.item("Loi N° 2021-03 Art 77 ; Arrêté n°2021-0069", "Notification des évènements indésirables"),
                b.item("BPDisp 7.52-7.59", "Vente en ligne : autorisation, médicaments non soumis à prescription"),
                b.item("", "Espace commandes en ligne, protocole emballage"),
                b.item("BPDisp 7.65", "Respect liste médicaments, taux de réduction (10%)"),
                b.item("BPDisp 7.60-7.64", "Livraison à domicile : habilitation, conditions de conservation"),
            ]},
            Section { id: 9, title: "Retours / Réclamations / Retraits / Rappels de lots".into(), items: vec![
                b.item("BPDisp 8.3, 8.9, 8.10", "Gestion des retours, médicaments défectueux, procédures de sécurité"),
                b.item("BPDisp 8.4", "Médicaments non utilisés rapportés par les particuliers"),
                b.item("BPDisp 8.5-8.8", "Produits récupérés : redistribution, stockage, stupéfiants"),
                b.item("BPDisp 8.12-8.13", "Retraits et rappels de lots, notification patients"),
            ]},
            Section { id: 10, title: "Destruction des déchets pharmaceutiques".into(), items: vec![
                b.item("BPDisp 9.2", "Gestion et destruction des déchets (déstockage, traçabilité)"),
            ]},
            Section { id: 11, title: "Préparations magistrales et officinales / Reconditionnement".into(), items: vec![
                b.pre("BPDisp 3.4-a ; 3.15 ; 4.10", "Personnel qualifié, local adapté avec préparatoire, équipements qualifiés"),
                b.item("", "Matière première : validité, eau purifiée, certificats d'analyse"),
                b.item("", "Procédures de préparation et reconditionnement, contrôles"),
                b.item("BPDisp 3.4", "Étiquetage des préparations, documentations spécifiques"),
                b.item("", "Libération de lot, retours, réclamations, prix"),
            ]},
            Section { id: 12, title: "Publicité / Pratique illégale / Gestion des PSQIF".into(), items: vec![
                b.item("Ord n°73-30 Art 27-35 ; BPDisp 1.20", "Publicité, échantillons, techniques promotionnelles, cadeaux"),
                b.item("Loi N° 2021-03 Art 54", "Pratique illégale : consultations, actes médicaux, soins infirmiers"),
                b.item("BPDisp 5.5", "Système prévention/détection/gestion PSQIF"),
            ]},
            Section { id: 13, title: "Auto-inspection / Audit interne".into(), items: vec![
                b.item("BPDisp 10.1-10.9", "Couverture du SMQ, exécution à intervalles réguliers, audits indépendants"),
                b.item("", "Enregistrement : traçabilité, comptes rendus, diffusion à l'équipe"),
                b.item("", "Mesures préventives et correctives par le pharmacien titulaire et le RMQ"),
                b.item("", "Suivi organisé : vérification de l'application et des résultats"),
            ]},
        ],
    }
}
